### PR TITLE
Modify modifier apply functions to remove stmtExprs

### PR DESCRIPTION
**Pull request by counc009**
Addresses initial suggestion in #147, removes use of stmtExpr so that qualifier mods can still result in lValues necessary for many productions.

### CODE REVIEW

**Comment by krame505** [comment]
Hey @TravisCarlson, care to take a look at some point?

**Comment by TravisCarlson** [comment]
> Hey @TravisCarlson, care to take a look at some point?

My comments are under #147. Do we still want to apply this pull request? From the last comments it looks like we were going to look into a different solution. Has anything changed since then?

**Comment by krame505** [comment]
Thanks Travis, I had forgotten about that discussion.

@counc009 is it OK to close this?

**Comment by counc009** [comment]
Yeah, I'm fine closing this.

**Pull request closed without merging**
