### PR TITLE
Misc. refactoring needed for Silver-ableC extension

### PR DESCRIPTION
**Pull request by krame505**
This branch contains some backwards-compatible changes in order to better support the ableC-Silver extension:
* Replace uses of `Identifier_t` and `TypeName_t` terminals with wrapper nonterminals `Identifier_c` and `TypeIdName_c`, in order to support ableC-to-Silver bridge productions for `Name`.  Extensions to be composed with ableC-Silver should be refactored in a similar way.  
* Add construction helpers for string constants and appending `Parameters`.
* Tweaks to IDE fonts (highlighting in Eclipse IDE built for composed Silver + ableC.)  
* Replace `//` regexes with `''` to work around our buggy implementation of ignore terminals that parses C comments anywhere in a Silver-ableC program.  

This branch (but not the modified downstream extensions) could probably be merged now, but shouldn't be deleted until I have the modified extensions building properly.

### CODE REVIEW

**Comment by krame505** [comment]
@tedinski Thoughts?  I'm primarily want your opinion on the concrete syntax refactoring.

**Comment by tedinski** [comment]
Mind reminding me on Tues? I'm a bit swamped at the moment.

**Comment by krame505** [comment]
Sure, here's your Tuesday reminder ;-)

This should get merged after #110 though, since I merged `fix/jenkins` into this in order to get started on Jenkins for silver-ableC.

**Comment by krame505** [comment]
@tedinski I just made a bunch of changes to Jenkins in order to support extensions using silver-ableC, so if you could take a look at that as well, that would be great.

**Comment by krame505** [comment]
Question: do you think that it would be a good idea "deploy" silver-ableC as a downloadable artifact on the melt website, similarly to silver?  For sure we will need to at least include this in our VM artifact, for the future.

**Comment by tedinski** [comment]
look fine. I only glanced at the jenkins-lib changes, they look okay. If there was something you were unsure about and thought needed more eyes, let me know.

**Comment by krame505** [comment]
I was also wondering about the concrete syntax refactor in this branch - any issues that I may have missed that arise when replacing `Identifier_t` and `TypeName_t` with nonterminals everywhere?  
Thanks

**Comment by tedinski** [comment]
It builds and tests pass, I can't think of anything that wouldn't have been exposed by that.

**Comment by krame505** [comment]
Thanks, I'll merge this tonight when I am back home, so I can manage if things break.

**Comment by krame505** [comment]
Merging this (and extensions) now...

**Pull request merged**
