### PR TITLE
AbleC 0.1.3 release

### PR DESCRIPTION
**Pull request by krame505**

### CODE REVIEW

**Comment by krame505** [comment]
Also if someone could review #151 so it can be merged before the release, that would be nice.

**Comment by ericvanwyk** [comment]
I approved #151.  Let me know when I can get the .tar.gz file for the digital repository.

**Comment by krame505** [comment]
Github will automatically create the tarball when I do the release.  I'll probably make the release tomorrow after I finish working on the paper responses.

**Comment by ericvanwyk** [comment]
Can you do one for silver-ableC too?  I'm not sure if this should be 0.1.0 or make it 0.1.3 to match the version of ableC, thoughts?

**Comment by krame505** [comment]
Previously we haven't been doing formal releases of silver-ableC, we've just been treating it like the other ableC extensions and doing a merge to master/tag corresponding to every ableC release.  But if we want a seperate tarball then an actual release of silver-ableC makes sense.  We probably want to release it through github as 0.1.0, but still add the ableC-0.1.3 tag pointing to the correct snapshot w.r.t. ableC.

**Comment by ericvanwyk** [comment]
Look here:
    https://github.com/melt-umn/silver-ableC/releases
This looks like a release of silver-ableC that is good enough.  It does generate a tarball that has just the contents of the silver-ableC repo.  So doing another one of these seems OK to me.  What do you think?

**Comment by krame505** [comment]
The "releases" tab shows all the tags - I didn't realize this generates a tarball as well.  But for consistency we probably want to also do an "actual" release, which is quick.  

I'm going to wait doing anything with releases until after we finish our work on the paper tomorrow (which is higher priority, right?)

**Comment by ericvanwyk** [comment]
We need to submit it to the DRUM to get the DOI that will go in the final version.  Tomorrow anytime is probably fine, but let's make sure we do it tomorrow.  Thanks.

**Pull request merged**
