### PR TITLE
Implement C11 anonymous structs and unions

### LINKED ISSUE #81: Anonymous unions not supported.
Test case:

```c
struct foo {
	enum {
		LEFT,
		RIGHT
	} disc;
	union {
		int i;
		float f;
	};
};

int main() {
	return 0;
}
```

Output on e44d98b:

```
Error at line 9, column 2 in file sad2.c
         (parser state: 296; real character index: 203):
  Expected a token of one of the following types:
   [edu:umn:cs:melt:ableC:concretesyntax:BlockComment,
    edu:umn:cs:melt:ableC:concretesyntax:Colon_t,
    edu:umn:cs:melt:ableC:concretesyntax:Identifier_t,
    edu:umn:cs:melt:ableC:concretesyntax:LParen_t,
    edu:umn:cs:melt:ableC:concretesyntax:LineComment,
    edu:umn:cs:melt:ableC:concretesyntax:NewLine_t,
    edu:umn:cs:melt:ableC:concretesyntax:Spaces_t,
    edu:umn:cs:melt:ableC:concretesyntax:Star_t,
    edu:umn:cs:melt:ableC:concretesyntax:cppTags:CPP_Location_Tag_t,
    edu:umn:cs:melt:ableC:concretesyntax:gcc_exts:PragmaMark]
   Input currently matches:
   [edu:umn:cs:melt:ableC:concretesyntax:Semi_t]
```

### PR DESCRIPTION
**Pull request by krame505**
Fixes #81.  

Nothing too tricky was required here, pretty much just adding some missing productions.

### CODE REVIEW

**Comment by ericvanwyk** [comment]
Cool - didn't know these existed...

**Comment by krame505** [comment]
Yeah, it's a nice feature for if you want to write something along the lines of
```
union foo {
  item_t items[5];
  struct {
   item_t item1, item2, item3, item4, item5;
  };
};
```
and be able to just do `foo.item1` instead of `foo.somefield.item1`.

**Comment by ericvanwyk** [comment]
It seems these are only allowed inside non-anonymous structs or union, right?  If so, do we check for this?

**Comment by krame505** [comment]
Not totally sure I understand what you are asking?  But you can nest them arbitrarily.

**Comment by ericvanwyk** [comment]
I guess I'm wondering if these can be top-level structs/unions.  It looks
like the anonymous ones lift their enclosed declarations up out of the
struct.  This wouldn't make sense at the top level of a declaration.

**Comment by krame505** [comment]
Oh.  Well, if somebody were to write a top-level struct that isn't also declaring a value, then it would just be a declaration of a new struct.

**Comment by krame505** [comment]
I would like to merge this soon if there are no objections.

**Pull request merged**
